"use client";

import { useOrder } from "@/context/order-context";

export function PromotionsSection() {
  const { addPromo, openDialog, setDrawerOpen } = useOrder();
  const addCombo = (key: string) => { addPromo(key); setDrawerOpen(true); };
  return <section className="promos" id="promos"><div className="container"><div className="reveal"><p className="eyebrow">Combos más pedidos</p><h2 className="section-title">Más pizza, <span className="red">más antojo</span></h2></div><article className="promo-feature reveal"><span className="promo-ribbon">Más pedida</span><div className="promo-feature-media" role="img" aria-label="Dos pizzas medianas de la promoción más pedida"/><div className="promo-feature-copy"><h3>Promo duo<br/><span className="promo-offer-ribbon">solo por <strong><b>$</b>10</strong></span><br/>2 pizzas</h3><p>Una Margarita con salsa, jamón y queso, más una Pepperoni con salsa, queso y pepperoni.</p><div className="promo-price-row"><strong className="promo-price">$10</strong><span className="promo-price-note">Para consumir<br/>en el local</span></div><div className="promo-takeaway"><strong>Para llevar o delivery:</strong> se añaden $2 por gastos de caja. La sede confirmará el costo del delivery.</div><button className="btn btn-yellow" type="button" onClick={() => openDialog("promo")}>Elegir esta promo</button></div></article><div className="combo-grid"><article className="combo-card reveal"><div><p className="eyebrow">3 pizzas · para compartir</p><h3>Quédate en casa</h3><p>Una grande, una mediana y una pequeña con jamón, pepperoni, vegetales y maíz.</p><div className="combo-bottom"><b>$25</b><button className="btn btn-yellow" type="button" onClick={() => addCombo("quedate")}>+ Agregar</button></div></div></article><article className="combo-card reveal"><div><p className="eyebrow">3 pizzas + refresco</p><h3>Full Family</h3><p>Una pizza de 36 cm, dos de 33 cm y refresco de 1.5 L. Queso, pepperoni, vegetales y maíz.</p><div className="combo-bottom"><b>$30</b><button className="btn btn-yellow" type="button" onClick={() => addCombo("full-family")}>+ Agregar</button></div></div></article></div></div></section>;
}
