const locations = [
  { name: "Unare II", detail: "Al lado del colegio Virgen Niña", href: "https://maps.google.com/?q=Unare+II+Colegio+Virgen+Ni%C3%B1a+Puerto+Ordaz" },
  { name: "Alta Vista", detail: "Detrás de la Clínica La Esperanza, frente al estacionamiento de Farmatodo", href: "https://maps.google.com/?q=Cl%C3%ADnica+La+Esperanza+Alta+Vista+Puerto+Ordaz" },
  { name: "Villa Brasil", detail: "Club La Cantera", href: "https://maps.google.com/?q=Club+La+Cantera+Villa+Brasil+Puerto+Ordaz" },
  { name: "San Félix", detail: "Urbanización Moreno de Mendoza", href: "https://maps.google.com/?q=Urbanizaci%C3%B3n+Moreno+de+Mendoza+San+F%C3%A9lix" },
];

export function VisitSection() {
  return <section className="visit" id="visitanos"><div className="container visit-grid"><div className="reveal"><p className="eyebrow">4 sedes · Bolívar</p><h2 className="section-title">Ven con <span className="red">hambre</span></h2><div className="locations">{locations.map((location, index) => <a key={location.name} className="location-card" href={location.href} target="_blank" rel="noopener"><span className="contact-icon" aria-hidden="true">{String(index + 1).padStart(2, "0")}</span><span><small>{location.name}</small><b>{location.detail}</b></span><span className="location-arrow" aria-hidden="true">↗</span></a>)}</div><div className="contact-list"><a className="contact-row" href="tel:+584148893707"><span className="contact-icon" aria-hidden="true">☎</span><span><small>Atención al cliente 1</small><b>0414 889 3707</b></span></a><a className="contact-row" href="tel:+584127094898"><span className="contact-icon" aria-hidden="true">☎</span><span><small>Atención al cliente 2</small><b>0412 709 4898</b></span></a><a className="contact-row" href="https://instagram.com/pizzashousepzo" target="_blank" rel="noopener"><span className="contact-icon" aria-hidden="true">◎</span><span><small>Síguenos</small><b>@pizzashousepzo</b></span></a></div></div><aside className="hours reveal"><h3>Horario del horno</h3><div className="hour-row"><span>Lunes — Jueves</span><span>5 pm — 12 am</span></div><div className="hour-row"><span>Viernes — Domingo</span><span>2 pm — 12 am</span></div><a className="btn" href="https://wa.me/584148893707?text=Hola%20Pizza%20House%2C%20quiero%20hacer%20un%20pedido" target="_blank" rel="noopener">Escribir por WhatsApp ↗</a></aside></div></section>;
}
