"use client";

import { fulfillmentNames, supportNumbers } from "@/data/catalog";
import { useOrder } from "@/context/order-context";
import { formatBs, formatUsd } from "@/lib/format";
import { DialogFrame } from "@/components/order/dialog-frame";

export function ConfirmationDialog() {
  const { cart, details, fulfillment, locationMethod, geoPlace, geoUrl, geoOutOfArea, totals, deliveryKm, bcvRate, whatsappUrl, closeDialog } = useOrder();
  return <DialogFrame name="confirm" title="Confirma tu pedido" description="Revisa los datos antes de abrir WhatsApp."><div className="confirm-order"><section className="confirm-section"><h3>Entrega</h3><div className="confirm-list"><div className="confirm-line"><span>Cliente</span><b>{details.customerName}</b></div><div className="confirm-line"><span>Modalidad</span><b>{fulfillmentNames[fulfillment]}</b></div><div className="confirm-line"><span>Sede</span><b>{details.branch}</b></div><div className="confirm-line"><span>Atención</span><b>{supportNumbers[details.supportPhone]}</b></div>{fulfillment === "delivery" && <><div className="confirm-line"><span>Sector</span><b>{locationMethod === "manual" ? details.sector : (geoPlace || "Por confirmar")}{geoOutOfArea ? " · Verificar zona" : ""}</b></div>{locationMethod === "gps" && <div className="confirm-line"><span>Ubicación</span><b><a className="gps-link" href={geoUrl} target="_blank" rel="noopener">GPS compartido ↗</a></b></div>}</>}</div></section><section className="confirm-section"><h3>Pedido</h3><div className="confirm-items">{cart.map((item) => <div className="confirm-item" key={item.id}><span><strong>{item.name}</strong><small>{item.detail}</small>{item.note && <small>Observación: {item.note}</small>}</span><b>{formatUsd(item.price)}</b></div>)}</div></section><section className="confirm-section"><h3>Total</h3><div className="confirm-list"><div className="confirm-line"><span>Subtotal</span><b>{formatUsd(totals.subtotal)}</b></div>{totals.packaging > 0 && <div className="confirm-line"><span>Gastos de caja</span><b>{formatUsd(totals.packaging)}</b></div>}{fulfillment === "delivery" && <div className="confirm-line"><span>Delivery{deliveryKm !== null ? ` · ${deliveryKm.toFixed(1)} km` : ""}</span><b>{totals.pendingDelivery ? "Por confirmar" : formatUsd(totals.delivery)}</b></div>}<div className="confirm-line"><span>Total estimado</span><b>{formatUsd(totals.total)}{totals.pendingDelivery ? " + delivery" : ""}</b></div><div className="confirm-line"><span>Total en Bs</span><b>{bcvRate ? `Bs ${formatBs(totals.total * bcvRate)}${totals.pendingDelivery ? " + delivery" : ""}` : "Por confirmar"}</b></div></div></section></div><div className="confirm-actions"><button className="btn btn-ghost" type="button" onClick={closeDialog}>Editar</button><a className="btn btn-yellow" href={whatsappUrl} target="_blank" rel="noopener">Confirmar y enviar ↗</a></div></DialogFrame>;
}
